import { DiBag } from '../../src';
const { withLifetime } = DiBag;
import type { Provider, Module, Bag } from '../../src';
import { withTokenBinding } from '../../src/provider';

export const graph = DiBag.createBuilder().register({
  db: withLifetime(() => ({ query: () => 1 }), 'root'),
  repo: withLifetime(({ db }: { db: { query(): number } }) => db.query(), 'root'),
}).build();
export const scoped = graph.createScope();
export const independent = graph.fork();
export const raw = withLifetime(DiBag.fromFactory(() => Promise.resolve({ id: 1 }), { acquisitionMode: 'raw' }), 'root');
export const native = withLifetime(DiBag.fromFactory(() => Promise.resolve({ id: 1 }), { acquisitionMode: 'nativePromise' }), 'transient');
export const metadata = DiBag.withMetadata(DiBag.withDisposal(raw, value => { const exact: Promise<{ id: number }> = value; void exact; }), { static: { owner: 'app' as const } });
export const builder = DiBag.createBuilder().register({ raw: metadata });
export const feature = DiBag.createBuilder().register({ raw: metadata }).buildModule(['raw']);
export const moduleBag = DiBag.createBuilder().installModule(feature).build();
export const capturing = DiBag.createBuilder().register({ scoped: () => 1, permissive: withLifetime(({ scoped }: { scoped: number }) => scoped, 'root', { allowScopedDependencies: true }), strict: withLifetime(({ permissive }: { permissive: number }) => permissive, 'root') }).build();
export const cycles = DiBag.createBuilder().register({ a: withLifetime(({ b }: { b: number }): number => b, 'transient'), b: withLifetime(({ a }: { a: number }): number => a, 'transient') }).build();
export const privateValid = DiBag.createBuilder().register({ db: withLifetime(() => 1, 'root'), bridge: withLifetime(({ db }: { db: number }) => db, 'transient') }).buildModule(['bridge']);
export const privateBag = DiBag.createBuilder().installModule(privateValid).register({ db: () => 1, root: withLifetime(({ bridge }: { bridge: number }) => bridge, 'root') }).build();
export const replacedRoot = DiBag.createBuilder().register({ db: () => 1, root: withLifetime(({ db }: { db: number }) => db, 'root') }).buildModule(['root']);
export const replacedBag = DiBag.createBuilder().installModule(replacedRoot).replace('root', () => 1).build();
export const renamedRoot = DiBag.createBuilder().register({ db: withLifetime(() => 1, 'root'), root: withLifetime(({ db }: { db: number }) => db, 'root') }).buildModule(['db', 'root']).renameExport('db', 'database');
export const renamedBag = DiBag.createBuilder().installModule(renamedRoot).build();
export const key: unique symbol = Symbol('root');
export const token = DiBag.token(key).of<number>();
export const bound = withTokenBinding(token, withLifetime(() => 1, 'root'));
export const rebound = withTokenBinding(token, DiBag.transformService(bound, { mode: 'direct', transform: value => value }));
export const tokenBag = DiBag.createBuilder().register(token, rebound).register({ root: withLifetime(DiBag.fromFunction([token], value => value), 'root') }).build();
export const tokenFork = tokenBag.fork([token], { [key]: withLifetime(() => 2, 'root') });
export const frames = DiBag.withMetadata(raw, { dynamic: { mode: 'direct', describe: () => ({ frame: 1 }) } });
export const asyncFrames = DiBag.withMetadata(withLifetime(() => 1, 'transient'), { dynamic: { mode: 'awaited', describe: () => ({}) } });
export const capability = DiBag.transformService(withLifetime(() => ({ read: () => Promise.resolve(1) }), 'root'), { mode: 'direct', transform: value => value.read(), ...{ acquisitionMode: 'raw' } });
export const mapped = DiBag.transformService(metadata, { mode: 'direct', transform: value => value, ...{ acquisitionMode: 'raw' } });
export const asyncMapped = DiBag.transformService(metadata, { mode: 'awaited', transform: value => value });
export const explicitDefault = withLifetime(() => 1, 'scoped');
export const defaultProvider: Provider<() => number> = explicitDefault;
export const defaultModule: Module<{ value: number }, Readonly<{}>> = DiBag.createBuilder().register({ value: explicitDefault }).buildModule(['value']);
export const defaultBag: Bag<{ value: () => number }> = DiBag.createBuilder().register({ value: () => 1 }).build();
export const mixed = Math.random() ? withLifetime(() => 1, 'root') : () => 1;
export const wrappedMixed = withLifetime(mixed, 'transient');
export const scopedCycle = DiBag.createBuilder().register({ a: ({ b }: { b: number }): number => b, b: withLifetime(({ a }: { a: number }): number => a, 'transient') }).build();
export const pureCycleRoot = DiBag.createBuilder().register({ a: withLifetime(({ b }: { b: number }): number => b, 'transient'), b: withLifetime(({ a }: { a: number }): number => a, 'transient'), root: withLifetime(({ a }: { a: number }) => a, 'root') }).build();
export const exportlessValid = DiBag.createBuilder().installModule(DiBag.createBuilder().register({ privateRoot: withLifetime(() => 1, 'root') }).buildModule([])).build();
export const renameCollisionValid = DiBag.createBuilder().register({ db: withLifetime(() => 1, 'root'), root: withLifetime(({ db, publicDb }: { db: number; publicDb: number }) => db + publicDb, 'root') }).buildModule(['db', 'root']).renameExport('db', 'publicDb');
export const renameCollisionBag = DiBag.createBuilder().installModule(renameCollisionValid).build();
export const reflectedScope = graph.createScope;
export const reflectedFork = graph.fork;
export const resetPolicy = withLifetime(withLifetime(() => 1, 'root', { allowScopedDependencies: true }), 'scoped');
export const replacedPrivateExport = DiBag.createBuilder().register({ db: () => 1, hidden: withLifetime(({ db }: { db: number }) => db, 'root') }).buildModule(['db']).renameExport('db', 'database');
export const replacedPrivateBag = DiBag.createBuilder().installModule(replacedPrivateExport).replace('database', withLifetime(() => 1, 'root')).build();
