import { DiBag, type Provider, type Module, type ProviderOutput, type ProviderAcquisitionMetadata, type ModuleExportedServices, type AcquisitionMetadataPresence } from '../../src';
import type { Assert, Equal } from './assert';
const key = Symbol('service'); const token = DiBag.createToken(key).forService<{ value: number }>();
const rewrapped = DiBag.createToken(key).forService<{ value: number }>();
const promiseKey = Symbol('promise'); const promiseToken = DiBag.createToken(promiseKey).forService<Promise<number>>();
const promised = Promise.resolve(3);
const source = DiBag.withMetadata(() => ({ value: 1, rich: true as const }), { static: { owner: 'team' } });
const bag = DiBag.createBuilder().withTokenService(token, source).withTokenService(promiseToken, () => promised).withServices({ read: DiBag.createProviderFromFunction({ dependencies: [rewrapped, promiseToken], factoryFunction: (value, promise) => ({ value: value.value, promise }) }) }).buildContainer();
const value = bag.resolve(rewrapped); const promise = bag.resolve(promiseToken); const inspection = bag.serviceSnapshot(token);
type Exact = [Assert<Equal<typeof value, { value: number; rich: true }>>, Assert<Equal<typeof promise, Promise<number>>>,
  Assert<Equal<typeof inspection.registrationMetadata, Readonly<{ owner: string }>>>];
const module = DiBag.createBuilder().withTokenService(token, source).buildModule({ exportedServiceKeys: [token] });
type Public = Assert<Equal<ModuleExportedServices<typeof module>, Readonly<{ [key]: { value: number; rich: true } }>>>;
const replaced = DiBag.createBuilder().withTokenService(token, source).withReplacedService(token, () => ({ value: 2, newer: true as const })).buildContainer().resolve(token);
type Replacement = Assert<Equal<typeof replaced, { value: number; newer: true }>>;
const moduleReplacement = DiBag.createBuilder().withTokenService(token, source).withReplacedService(token, () => ({ value: 3, module: true as const })).buildModule({ exportedServiceKeys: [token] });
const moduleValue = DiBag.createBuilder().withInstalledModules([moduleReplacement]).buildContainer().resolve(token);
type ModuleReplacement = Assert<Equal<typeof moduleValue, { value: number; module: true }>>;
const namedNeeds = ({ name }: { name: string }) => ({ value: name.length });
DiBag.createBuilder().withTokenService(token, namedNeeds).withServices({ name: () => 'ok' }).buildContainer();
DiBag.createBuilder().withServices({ name: () => 'ok' }).withTokenService(token, namedNeeds).buildContainer();
const plainModule: Module<{ value: number }, {}> = DiBag.createBuilder().withServices({ value: () => 1 }).buildModule({ exportedServiceKeys: ['value'] });
const plainProvider: Provider<() => number> = DiBag.createProviderFromFunction({ dependencies: [], factoryFunction: () => 1 });
const frameSource = DiBag.createProviderFromFunction({ dependencies: [promiseToken], factoryFunction: promise => promise });
const framed = DiBag.withMetadata(frameSource, { dynamic: { mode: 'direct', describe: () => ({ source: 'frame' }) } });
const frameBag = DiBag.createBuilder().withInstalledModules([DiBag.createBuilder().withServices({ framed }).buildModule({ exportedServiceKeys: ['framed'] })]).withTokenService(promiseToken, () => promised).buildContainer();
const frameInspection = frameBag.serviceSnapshot('framed');
type Frames = [Assert<Equal<ProviderOutput<typeof framed>, Promise<number>>>, Assert<Equal<typeof frameInspection.acquisitions[number]['acquisitionMetadata'], AcquisitionMetadataPresence<ProviderAcquisitionMetadata<typeof framed>>>>];
const framedKey = Symbol('framed'); const framedToken = DiBag.createToken(framedKey).forService<Promise<number>>();
const boundFrames = DiBag.createBuilder().withInstalledModules([DiBag.createBuilder().withTokenService(framedToken, framed).buildModule({ exportedServiceKeys: [framedToken] })]).withTokenService(promiseToken, () => promised).buildContainer().serviceSnapshot(framedToken);
type BoundFrames = Assert<Equal<typeof boundFrames.acquisitions[number]['acquisitionMetadata'], AcquisitionMetadataPresence<ProviderAcquisitionMetadata<typeof framed>>>>;
const tokenOverride = DiBag.createProviderFromFunction({ dependencies: [promiseToken], factoryFunction: promise => ({ value: 2, rich: true as const }) });
const child = bag.createIndependentContainer([token], { [key]: tokenOverride });
type Child = Assert<Equal<ReturnType<typeof child.resolve<typeof token>>, { value: number; rich: true }>>;
void [plainModule, plainProvider];
