import { DiBag, type Provider, type Module, type ProviderOutput, type ProviderAcquisitionMetadata, type ModuleExportedServices, type AcquisitionMetadataPresence } from '../../src';
import type { Assert, Equal } from './assert';
const key = Symbol('service'); const token = DiBag.token(key).of<{ value: number }>();
const rewrapped = DiBag.token(key).of<{ value: number }>();
const promiseKey = Symbol('promise'); const promiseToken = DiBag.token(promiseKey).of<Promise<number>>();
const promised = Promise.resolve(3);
const source = DiBag.withMetadata(() => ({ value: 1, rich: true as const }), { static: { owner: 'team' } });
const bag = DiBag.createBuilder().register(token, source).register(promiseToken, () => promised).register({ read: DiBag.fromFunction([rewrapped, promiseToken], (value, promise) => ({ value: value.value, promise })) }).build();
const value = bag.resolve(rewrapped); const promise = bag.resolve(promiseToken); const inspection = bag.inspect(token);
type Exact = [Assert<Equal<typeof value, { value: number; rich: true }>>, Assert<Equal<typeof promise, Promise<number>>>,
  Assert<Equal<typeof inspection.registrationMetadata, Readonly<{ owner: string }>>>];
const module = DiBag.createModuleBuilder().register(token, source).buildModule([token]);
type Public = Assert<Equal<ModuleExportedServices<typeof module>, Readonly<{ [key]: { value: number; rich: true } }>>>;
const replaced = DiBag.createBuilder().register(token, source).replace(token, () => ({ value: 2, newer: true as const })).build().resolve(token);
type Replacement = Assert<Equal<typeof replaced, { value: number; newer: true }>>;
const moduleReplacement = DiBag.createModuleBuilder().register(token, source).replace(token, () => ({ value: 3, module: true as const })).buildModule([token]);
const moduleValue = DiBag.createBuilder().installModule(moduleReplacement).build().resolve(token);
type ModuleReplacement = Assert<Equal<typeof moduleValue, { value: number; module: true }>>;
const namedNeeds = ({ name }: { name: string }) => ({ value: name.length });
DiBag.createBuilder().register(token, namedNeeds).register({ name: () => 'ok' }).build();
DiBag.createBuilder().register({ name: () => 'ok' }).register(token, namedNeeds).build();
const plainModule: Module<{ value: number }, {}> = DiBag.createModuleBuilder().register({ value: () => 1 }).buildModule(['value']);
const plainProvider: Provider<() => number> = DiBag.fromFunction([], () => 1);
const frameSource = DiBag.fromFunction([promiseToken], promise => promise);
const framed = DiBag.withMetadata(frameSource, { dynamic: { mode: 'direct', describe: () => ({ source: 'frame' }) } });
const frameBag = DiBag.createBuilder().installModule(DiBag.createModuleBuilder().register({ framed }).buildModule(['framed'])).register(promiseToken, () => promised).build();
const frameInspection = frameBag.inspect('framed');
type Frames = [Assert<Equal<ProviderOutput<typeof framed>, Promise<number>>>, Assert<Equal<typeof frameInspection.acquisitions[number]['acquisitionMetadata'], AcquisitionMetadataPresence<ProviderAcquisitionMetadata<typeof framed>>>>];
const framedKey = Symbol('framed'); const framedToken = DiBag.token(framedKey).of<Promise<number>>();
const boundFrames = DiBag.createBuilder().installModule(DiBag.createModuleBuilder().register(framedToken, framed).buildModule([framedToken])).register(promiseToken, () => promised).build().inspect(framedToken);
type BoundFrames = Assert<Equal<typeof boundFrames.acquisitions[number]['acquisitionMetadata'], AcquisitionMetadataPresence<ProviderAcquisitionMetadata<typeof framed>>>>;
const tokenOverride = DiBag.fromFunction([promiseToken], promise => ({ value: 2, rich: true as const }));
const child = bag.fork([token], { [key]: tokenOverride });
type Child = Assert<Equal<ReturnType<typeof child.resolve<typeof token>>, { value: number; rich: true }>>;
void [plainModule, plainProvider];
