// GENERATED by scripts/generate-removed-api.mjs from tools/codemod/rename-map.json. Do not edit by hand.
import { libraryError } from './errors';

/** Every callable name that 0.5.0 removed, by the 0.4.0 declaration that owned it, with what replaces it. */
export const removedApi: Readonly<Record<string, Readonly<Record<string, string>>>> = Object.freeze({
  "Bag": {
    "createScope": "container.createChildContainer(replacedServiceKeys, replacementProviders, { sharedParentServiceKeys }); use container.createChildContainer() or container.createChildContainer({ sharedParentServiceKeys }) when no services are replaced",
    "fork": "container.createIndependentContainer(replacedServiceKeys, replacementProviders); use container.createIndependentContainer() when no services are replaced",
    "inspect": "container.serviceSnapshot(serviceKey)",
    "inspectAll": "container.serviceSnapshot(collectionToken); create collectionToken with DiBag.createToken(symbol).forCollectionOf<Item>(), and manually split any mixed single-service and collection uses into tokens with distinct symbols",
    "inspectGraph": "container.graphSnapshot()",
    "resolveAll": "container.resolveCollection(collectionToken); create collectionToken with DiBag.createToken(symbol).forCollectionOf<Item>(), and manually split any mixed single-service and collection uses into tokens with distinct symbols",
  },
  "Builder": {
    "alias": "builder.withServiceAlias({ aliasKey, targetServiceKey })",
    "build": "builder.buildContainer",
    "buildAndStart": "builder.buildContainer().ensureServicesReady(serviceKeys, options); rename signal to abortSignal and timeoutMs to totalTimeoutMs; replace startupOrder with maxConcurrentServiceKeys (omit for parallel, 1 for sequential, or the number); options may be omitted",
    "contribute": "builder.withCollectionContribution({ collectionToken, provider }); create collectionToken with DiBag.createToken(symbol).forCollectionOf<Item>()",
    "installModule": "builder.withInstalledModules([module])",
    "register": "builder.withServices({ key: provider }) or builder.withTokenService(token, provider)",
    "replace": "builder.withReplacedService",
    "verifyGraph": "builder.verifyGraphAtCompileTime",
  },
  "DiBagApi": {
    "all": "the collection token itself, from DiBag.createToken(symbol).forCollectionOf<Item>()",
    "fromAsyncFactory": "DiBag.createProvider(factory, { factoryReturnKind: 'native-promise' }); add factoryReceivesContext: true if the old call used context: 'acquisition'",
    "fromClass": "DiBag.createProviderFromClass({ dependencies, serviceClass }); move any acquisitionMode option into this object as factoryReturnKind (auto -> auto-detect, raw -> uninspected, nativePromise -> native-promise)",
    "fromFactory": "DiBag.createProvider(factory, options); rename acquisitionMode to factoryReturnKind (auto -> auto-detect, raw -> uninspected, nativePromise -> native-promise) and context: 'acquisition' to factoryReceivesContext: true; options may be omitted",
    "fromFunction": "DiBag.createProviderFromFunction({ dependencies, factoryFunction }); move any acquisitionMode option into this object as factoryReturnKind (auto -> auto-detect, raw -> uninspected, nativePromise -> native-promise)",
    "fromPlugin": "DiBag.createProviderFromPlugin({ dependencies, pluginDescriptor, factoryReturnKind, isValidPluginOutput }); rename validate to isValidPluginOutput and map acquisitionMode raw -> uninspected or nativePromise -> native-promise",
    "fromSyncFactory": "DiBag.createProvider(factory, { factoryReturnKind: 'sync-value' }); add factoryReceivesContext: true if the old call used context: 'acquisition'",
    "token": "DiBag.createToken(symbol).forService<Service>() or DiBag.createToken(symbol).forCollectionOf<Item>(); choose the kind manually from its uses, and split mixed single-service and collection uses into tokens with distinct symbols",
    "transformService": "DiBag.providerWithTransformedService({ provider, transformService, callbackReceives }); map mode direct -> exposed-service or awaited -> fulfilled-value; for exposed-service callbacks, rename acquisitionMode to transformReturnKind (auto -> auto-detect, raw -> uninspected, nativePromise -> native-promise)",
    "withDisposal": "DiBag.providerWithDisposal({ provider, disposeService })",
    "withLifetime": "DiBag.providerWithLifetime({ provider, lifetime }); map root -> singleton:one-per-container-tree, scoped -> scoped:one-per-container, or transient -> transient:one-per-resolve; move allowScopedDependencies into this object as allowsScopedDependencies",
    "withMetadata": "DiBag.providerWithRegistrationMetadata({ provider, registrationMetadata }) for static metadata, or DiBag.providerWithAcquisitionMetadata({ provider, describeAcquisition, callbackReceives }) for dynamic metadata; map mode direct -> exposed-service or awaited -> fulfilled-value; combined static and dynamic metadata requires manually composing both calls while preserving evaluation order",
  },
  "Module": {
    "renameExport": "module.withRenamedExport({ currentExportKey, newExportKey })",
  },
  "token()": {
    "of": "DiBag.createToken(symbol).forService<Service>() or DiBag.createToken(symbol).forCollectionOf<Item>(); choose the kind manually from its uses, and split mixed single-service and collection uses into tokens with distinct symbols",
  },
});

const stubs = new WeakSet<object>();
/** True for a function that exists only to say that a 0.4.0 name is gone. */
export function isRemovedApiStub(value: unknown): boolean { return typeof value === 'function' && stubs.has(value); }

function stub(owner: string, name: string, replacement: string): () => never {
  const removedApiStub = (): never => {
    throw libraryError('DI_BAG_REMOVED_API', `${name} was removed in 0.5.0; use ${replacement}`, { operation: name, removed: `${owner}.${name}`, replacement });
  };
  stubs.add(removedApiStub);
  return removedApiStub;
}

/**
 * Define the stubs of one owner on a class prototype, or on a plain object such as the facade BEFORE it is frozen.
 * A stub is not enumerable, so Object.keys(DiBag) lists only the live API, and it never replaces a member the target still has.
 */
export function installRemovedMembers(owner: string, target: object): void {
  for (const [name, replacement] of Object.entries(removedApi[owner] ?? {})) {
    if (name in target) continue;
    Object.defineProperty(target, name, { value: stub(owner, name, replacement), enumerable: false, configurable: false, writable: false });
  }
}
